.\" (C) Copyright 2021 Arturo Borrero Gonzalez <aborrero@wikimedia.org>
.\"
.TH TOOLFORGE-JOBS-FRAMEWORK 1 "October 10 2022"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
toolforge-jobs-framework-cli \- command line interface for the Toolforge Jobs Framework
.SH SYNOPSIS
.B toolforge-jobs [options] {images,run,show,list,delete,flush,load,restart} ...
.SH DESCRIPTION
The \fBtoolforge-jobs\fP command line interface allows you to interact with the \fBToolforge
Jobs Framework\fP.

This framework allows you to manage jobs that run in the \fBWikimedia Toolforge\fP platform.

In general there are 3 kind of jobs:
.TP
.B normal
Jobs that are initiated by the user, and are expected to run until the job's internal execution
normally finishes.
.TP
.B schedule
Jobs that once created by the user, are periodically launched at a given time by the framework.
Similar to a cronjob.
.TP
.B continuous
Jobs that once created by the user are expected to be always up and running (for example, a daemon).

.SH ACTIONS
Top level actions that the command supports:

.TP
.B images
List information on available container image types for the \fBToolforge Jobs Framework\fP. To be used in
the \fBrun\fP command \fB--image\fP parameter.

Container images marked as \fBDEPRECATED\fP should be avoided in general.

Example:

.nf
$ toolforge-jobs images
+--------------------------+------------------------------------------------------------------------+
|        Short name        |                           Container image URL                          |
+--------------------------+------------------------------------------------------------------------+
|     tf-bullseye-std      | docker-registry.tools.wmflabs.org/toolforge-bullseye-standalone:latest |
| tf-buster-std-DEPRECATED |  docker-registry.tools.wmflabs.org/toolforge-buster-standalone:latest  |
|        tf-golang         |  docker-registry.tools.wmflabs.org/toolforge-golang-sssd-base:latest   |
|       tf-golang111       | docker-registry.tools.wmflabs.org/toolforge-golang111-sssd-base:latest |
|         tf-jdk17         |   docker-registry.tools.wmflabs.org/toolforge-jdk17-sssd-base:latest   |
|   tf-jdk11-DEPRECATED    |   docker-registry.tools.wmflabs.org/toolforge-jdk11-sssd-base:latest   |
|    tf-jdk8-DEPRECATED    |   docker-registry.tools.wmflabs.org/toolforge-jdk8-sssd-base:latest    |
|        tf-node12         |  docker-registry.tools.wmflabs.org/toolforge-node12-sssd-base:latest   |
|   tf-node10-DEPRECATED   |  docker-registry.tools.wmflabs.org/toolforge-node10-sssd-base:latest   |
|   tf-node6-DEPRECATED    |   docker-registry.tools.wmflabs.org/toolforge-node6-sssd-base:latest   |
|    tf-php5-DEPRECATED    |   docker-registry.tools.wmflabs.org/toolforge-php5-sssd-base:latest    |
|   tf-php72-DEPRECATED    |   docker-registry.tools.wmflabs.org/toolforge-php72-sssd-base:latest   |
|   tf-php73-DEPRECATED    |   docker-registry.tools.wmflabs.org/toolforge-php73-sssd-base:latest   |
|         tf-php74         |   docker-registry.tools.wmflabs.org/toolforge-php74-sssd-base:latest   |
|  tf-python2-DEPRECATED   |  docker-registry.tools.wmflabs.org/toolforge-python2-sssd-base:latest  |
|  tf-python34-DEPRECATED  | docker-registry.tools.wmflabs.org/toolforge-python34-sssd-base:latest  |
|  tf-python35-DEPRECATED  | docker-registry.tools.wmflabs.org/toolforge-python35-sssd-base:latest  |
|  tf-python37-DEPRECATED  | docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest  |
|       tf-python39        | docker-registry.tools.wmflabs.org/toolforge-python39-sssd-base:latest  |
|   tf-ruby21-DEPRECATED   |  docker-registry.tools.wmflabs.org/toolforge-ruby21-sssd-base:latest   |
|   tf-ruby25-DEPRECATED   |  docker-registry.tools.wmflabs.org/toolforge-ruby25-sssd-base:latest   |
|        tf-ruby27         |  docker-registry.tools.wmflabs.org/toolforge-ruby27-sssd-base:latest   |
|         tf-tcl86         |   docker-registry.tools.wmflabs.org/toolforge-tcl86-sssd-base:latest   |
|       wm-bullseye        |      docker-registry.tools.wmflabs.org/wikimedia-bullseye:latest       |
|   wm-buster-DEPRECATED   |       docker-registry.tools.wmflabs.org/wikimedia-buster:latest        |
|  wm-stretch-DEPRECATED   |       docker-registry.tools.wmflabs.org/wikimedia-stretch:latest       |
+--------------------------+------------------------------------------------------------------------+
.fi

.TP
.B run NAME --command COMMAND --image IMAGE --no-filelog --mem MEM --cpu CPU [--schedule SCHEDULE | --continuous | --wait]
Run a new job of your own in Toolforge. Action specific parameters:

.nf
NAME                    New job name, unique identifier. Example: "myjob"
--command COMMAND       The command to run in the job. Example: "./mycommand.sh argone --argtwo"
--image IMAGE           Container image shortname. Check them with the \fBcontainers\fP action. Example: "tf-bullseye-std".
--no-filelog            Disable log storage in files in the tool home directory.
--mem MEM               Request additional memory resource limits for the job.
--cpu CPU               Request additional CPU resource limits for the job
--emails OPT            Specify if you want to receive emails about events for this job. Choices are 'none', 'all', 'onfailure', 'onfinish'. The default is 'none'.

--schedule SCHEDULE     If the job is a schedule, cron time specification. Example: "1 * * * *".
--continuous            Run a continuous job.
--wait                  Run a normal job and wait for completition.
.fi

Some complete examples:

.nf
Running a normal job:
$ toolforge-jobs run myjob --command ./mycommand.sh --image tf-bullseye-std

Running a normal job and waiting for it to complete:
$ toolforge-jobs run myotherjob --command ./myothercommand.sh --image tf-bullseye-std --wait

Running a continuous job:
$ toolforge-jobs run myalwaysrunningjob --command ./myendlesscommand.sh --image tf-bullseye-std --continuous

Running a scheduled job:
$ toolforge-jobs run mycronjob --command ./everyminute.sh --image tf-bullseye-std --schedule "1 * * * *"

Running a normal job without logs being stored:
$ toolforge-jobs run myjob --command ./mycommand.sh --image tf-bullseye-std --no-filelog --emails none

Running a job with command arguments:
$ toolforge-jobs run myjob --command "./mycommand.sh --witharguments" --image tf-bullseye-std --emails all

Running a job requesting additional CPU and memory:
$ toolforge-jobs run myjob --command "./heavycommand.sh" --image tf-bullseye-std --mem 1Gi --cpu 10
.fi

.TP
.B show NAME
Show details of a job of your own in Toolforge.

Example:

.nf
$ toolforge-jobs show myscheduledjob
+------------+-----------------------------------------------------------------+
| Job name:  | myscheduledjob                                                  |
+------------+-----------------------------------------------------------------+
| Command:   | ./read-dumps.sh myargument                                      |
+------------+-----------------------------------------------------------------+
| Job type:  | schedule: * * * * *                                             |
+------------+-----------------------------------------------------------------+
| Container: | tf-bullseye-std                                                 |
+------------+-----------------------------------------------------------------+
| File log:  | yes                                                             |
+------------+-----------------------------------------------------------------+
| Emails:    | none                                                            |
+------------+-----------------------------------------------------------------+
| Resources: | mem: 10Mi, cpu: 100                                             |
+------------+-----------------------------------------------------------------+
| Status:    | Last schedule time: 2021-06-30T10:26:00Z                        |
+------------+-----------------------------------------------------------------+
| Hints:     | Last run at 2021-06-30T10:26:08Z. Pod in 'Pending' phase. State |
|            | 'waiting' for reason 'ContainerCreating'.                       |
+------------+-----------------------------------------------------------------+
.fi

.TP
.B list [-l|--long]
List all running jobs of your own in Toolforge.

The \fB-l\fP (or \fB--long\fP) parameter indicates if additional fields should be displayed.

Example, short listing:

.nf
$ toolforge-jobs list
Job name:       Job type:            Status:
--------------  -------------------  ---------------------------
myscheduledjob  schedule: * * * * *  Last schedule time: 2021-06-30T10:26:00Z
alwaysrunning   continuous           Running
myjob           normal               Completed
.fi

Example, long listing:

.nf
$ toolforge-jobs list -l
Job name:       Command:                 Job type:            Container:        File log:  Emails:   Resources:   Status:
--------------  -----------------------  -------------------  ---------------   ---------  -------   ----------   ---------------------------
myscheduledjob  ./read-dumps.sh          schedule: * * * * *  tf-bullseye-std   yes        none      default      Last schedule time: 2021-06-30T10:26:00Z
alwaysrunning   ./myendlesscommand.sh    continuous           tf-bullseye-std   no         all       default      Running
myjob           ./mycommand.sh --debug   normal               tf-bullseye-std   yes        onfinish  default      Completed
.fi

.TP
.B delete NAME
Delete a running job of your own in Toolforge.
.TP
.B flush
Delete all running jobs of your own in Toolforge.
.TP
.B load FILE
Flush all jobs (similar to \fBflush\fP action) and read a YAML file with job specifications to be
loaded and run all at once.

Loading new jobs will stop if failures are found.

The file format mirrors arguments to the \fBrun\fP action.

Example YAML file:

.nf
---
# a cronjob
- name: everyminute
  command: ./myothercommand.py -v
  image: tf-bullseye-std
  no-filelog: true
  schedule: "* * * * *"
  emails: onfailure
# a continuous job
- image: tf-bullseye-std
  name: endlessjob
  command: ./dumps-daemon.py --endless
  continuous: true
  emails: all
# wait for this normal job before loading the next
- name: myjob
  image: tf-bullseye-std
  command: ./mycommand.sh --argument1
  wait: true
  emails: onfinish
# another normal job after the previous one finished running
- name: anotherjob
  image: tf-bullseye-std
  command: ./mycommand.sh --argument1
  emails: none
.fi

Alternatively, the \fB--job NAME\fP parameter can be used to load (and delete the old one, if it
exists) a single job only.
.TP
.B restart NAME
Restarts a currently running job. Only continuous and cron jobs are supported.

.SH OPTIONS
Normal users wont need any of these options, which are mostly for Toolforge administrators, and
only documented here for completeness.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-debug
Activate debug mode.
.TP
.B \-\-cfg PATH
Specify path to a YAML configuration file for the Toolforge Jobs Framework command line interface.
If not specified, the default is \fB/etc/toolforge-jobs-framework-cli.cfg\fP.

This configuration allows to modify the framework environment and some behavior aspects.

Example YAML configuration file:

.nf
---
api_url: https://jobs.svc.tools.eqiad1.wikimedia.cloud:30001/api/v1
kubeconfig: ~/.kube/config
customhdr: { 'hdr': 'true' }
customaddr: 127.0.0.1
customfqdn: jobs.svc.toolsbeta.eqiad1.wikimedia.cloud
.fi


.SH SEE ALSO
.nf
* https://wikitech.wikimedia.org/wiki/Portal:Toolforge
* https://wikitech.wikimedia.org/wiki/Help:Toolforge/Jobs_framework
* https://jobs.toolforge.org/
.fi

.SH AUTHOR
\fBWikimedia Toolforge\fP is a service provided by the \fBWikimedia Foundation Cloud Services\fP team.

The \fBToolforge Job Framework\fP was initially designed and written by
\fBArturo Borrero Gonzalez\fP.
